### ISSUE TITLE
code problems

### ISSUE THREAD

**Issue by swt9991** [uvavision/SimVQA#1]
Hello author, I have recently reproduced the SimVQA code you gave, but in the process of reproduction, I found that the code you gave in your article/ BOTTOM_ UP/bottom-up-attention/train_ coco_ pt1_ marshal.p、./BOTTOM_ UP/bottom-up-attention/train_ coco_ pt2_ Marshal. p and other files are not in the given package. I want to ask you how to solve it?

**Comment by pcascanteb** [comment]
Hello, I'm really sorry. I just saw this!

Those are quite large files containing features precomputed using the [bottom-up-attention code](https://github.com/peteanderson80/bottom-up-attention). First, make sure you clone that repo and install all dependencies so that you are able to run their [demo code](https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/demo.py).

We basically use Faster R-CNN to extract the image features and collect them by the predicted pseudo label. We store those features in a dictionary, so we don't have to re-compute every time we train or evaluate. To do so, please check the following code: https://colab.research.google.com/drive/1_4Zz_d1kNNUl7rwyS0wUN8RwKQn1UOoq?usp=sharing 

You can split the whole dataset into chunks of N images so that each pickle file is not prohibitively huge (it also depends on your CPU capacity to store all features in memory) -- we then use marshal to dump/load the pre-computed features.

I hope this helps!

**Comment by swt9991** [comment]
你好 消息wt已收到 wt近期较忙碌 勿着急

**Comment by swt9991** [comment]
你好 消息wt已收到 wt近期较忙碌 勿着急
